### PR TITLE
Add seed:migrate:status task and .check_pending!

### PR DESCRIPTION
**Pull request by tbloncar**
These commits address #39 and #40.

### CODE REVIEW

**Comment by tbloncar** [comment]
Ah. I can also document these features in the README should we decide to move forward with them.

**Comment by pjambet** [comment]
This looks pretty cool, thank you so much for this. I'll try to give it a thorough review in the next few days.

Thanks again!

**Comment by pjambet** [comment]
Sorry about the (very) late reply.

This is awesome, can you add a section to the README to explain the new tasks?

Thank you so much for your collaboration!

**Comment by tbloncar** [comment]
Thanks, @pjambet. I'll get on the README updates as soon as I get a chance.

**Comment by tbloncar** [comment]
README updates have been made.

**Comment by pjambet** [comment]
That's awesome, thank you!

I'm seeing a bunch of failures, they don't seem related, but I'm taking a look at it now before merging this.

**Comment by pjambet** [comment]
I released version 1.2.0 on rubygems yesterday, thank you again!

**Pull request merged**
