### PR TITLE
Fix migration rollback instruction in README

### PR DESCRIPTION
**Pull request by jmyers0022**
Thanks for the awesome Gem!

Just a quick documentation fix to show the proper argument to be called for a rollback for a certain number of migrations.

### CODE REVIEW

**Comment by pjambet** [comment]
Hey, thanks for this PR.

I was looking at the code and it seems like `STEPS` should work too: https://github.com/harrystech/seed_migration/blob/2749ec253770de3e2c14e9d4cd4c7c77d89972b7/lib/tasks/seed_migration_tasks.rake#L9

Did you have any issues using `STEPS` and not `STEP`?

**Comment by jmyers0022** [comment]
Ahh. Yep I was having issues using `STEPS`, but it appears that it's due to me not having the latest version. I had forked this last summer when we started using it and haven't updated my local copy since.

Still might be worth changing since some folks may be on older versions. Also the Rails migration rollbacks use `STEP`.

Thanks again for the gem. It's worked out really well for us. I think one of the guys on our team even bought a sweet razor from you.

**Comment by pjambet** [comment]
Good points, merging this right away. I was actually wondering if the code was actually working as expected.

Thanks again!.

**Comment by danielschwartz** [comment]
The best option here would be to cherrypick this commit into the tag before this issue was fixed. Unfortunately (or maybe fortunately), that would break a [cardinal rule](http://stackoverflow.com/questions/21459540/add-new-commit-in-the-existing-git-tag) of git.

**Comment by danielschwartz** [comment]
@pjambet both STEP and STEPS are correct, it might make more sense to actually call out the version this changed in on the master README.

**Pull request merged**
