### PR TITLE
Add rails 5.2 to travis config

### PR DESCRIPTION
**Pull request by timhaines**

### CODE REVIEW

**Comment by timhaines** [comment]
@pjambet Thanks for taking a look!  I pushed a commit updating the mysql2 gem to 0.5.2.  This is the mysql2 version that the `rails new` command installs currently.

I'm not sure if my third-party commits are creating travis builds?  I'll take a look.

**Comment by timhaines** [comment]
I see they are here: https://travis-ci.org/harrystech/seed_migration/builds/488227646

**Comment by timhaines** [comment]
@pjambet I suspect the postgresql failures are unrelated.  Can you trigger travis to rerun tests for the latest master branch commit?

**Comment by pjambet** [comment]
I triggered a rebuild on master and it failed! https://travis-ci.org/harrystech/seed_migration/builds/312107534

I don't have the time to look into it now though, and I have a pretty busy week ahead of me.

**Comment by timhaines** [comment]
@pjambet thank you!  I think that's a fairly good indicator that this PR didn't introduce the PG problems.  😄   

I've never really used PG, so don't really have any experience to lean on to help out.

**Comment by pjambet** [comment]
Makes sense, I guess it makes sense to merge it then.

Thank you again for your help with this!

**Pull request merged**
